# Generated by Django 5.0.6 on 2024-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_form',
            field=models.CharField(default=1, max_length=155, verbose_name='Дата создание 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='food1',
            field=models.CharField(default=1, max_length=155, verbose_name='Еда 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='food2',
            field=models.CharField(default=1, max_length=155, verbose_name='Еда 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_to',
            field=models.CharField(max_length=155, verbose_name='Дата создание 1'),
        ),
    ]
